name: Vix Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,8,16 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets..ACTIONS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run VixProxy script
        run: |
          python VixProxy.py

      - name: Commit and push updated files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          if [ -f VixFlim.m3u8 ]; then git add VixFlim.m3u8; fi
          if [ -f film_cache.json ]; then git add film_cache.json; fi
          if ! git diff --cached --quiet; then
            git commit -m "🔄 Auto-update playlist $(date '+%Y-%m-%d %H:%M')"
            git push origin main
          else
            echo "✅ No changes to commit"
          fi
        continue-on-error: false
